version: "3"
services:
    webapp:
        build: 
            context: .
            dockerfile: Dockerfile.dev
        ports:
            - "4006:4000"
        volumes: 
            - /usr/local/lib/node_modules 
            - .:/app